### ISSUE TITLE
Option to make slaves read only

### ISSUE THREAD

**Issue by leoleovich** [outbrain/orchestrator#130]
Would be nice to have configurable option to make slaves read only by default.
Thanks.

**Comment by shlomi-noach** [comment]
How do you mean "by default"? Should it modify any existing slave? Or upon `CHANGE MASTER TO`?
Why are the slaves not `read_only` to begin with?

**Comment by leoleovich** [comment]
If slave is not master - always be read only. If it became slave and master or just master - allow writing. This will prevent breaking replication in case someone wrote something on slave and after orchestrator made an failover.

**Comment by shlomi-noach** [comment]
We're not speaking the same language here. What I'm asking is -- when and why exactly do you expect orchestrator to set your slaves as read-only? 
- Anytime it sees a slave? (wrong way of doing this) 
- After master promotion? (wrong, because orchestrator does not handle the dead master -- it's dead ; and the other slaves were already slaves before that)
- when? And why?

**Comment by leoleovich** [comment]
I thought about:
Having slave read only all the time if it is not a master at the same time.

**Comment by shlomi-noach** [comment]
This is a WontFix. It is not orchestrator's ownership to do so.
Why would that slave not be read-only in your scenario, in the first place?
In our setups, we have several valid cases for some slaves to not be read-only. Orchestrator cannot understand the reasoning behind this and this is left for puppet.

I would suggest your puppet/chef/ansible/whatever should take care of that.
