### ISSUE TITLE
Show GTID related status

### ISSUE THREAD

**Issue by JohanTan** [outbrain/orchestrator#216]
I am unable to find GTID status for each server such as Transaction executed and transaction purged. Also "Skip query"  with GTID mode enabled seems sketchy try. Is there a way to insert empty transaction for GTID mode? Thanks!

**Comment by shlomi-noach** [comment]
Apologies for the late response; I had notifications misconfigured.

The issue is titles "Show GTID related status" yet you ask about injecting an empty transaction for GTID. So I'll try and answer both.

Orchestrator actually records:

- executed_gtid_set
- gtid_purged

but does not show it up on the web interface. If this is a request, then it can be done; let me know if this is what you are looking for.

As for injecting an empty transaction; yeah, I'm unhappy with current implementation. I'm not using GTID myself at this time, and haven't touched it in the past 8 months or so. I have some rejections to GTID. This is to explain I'm not the expert on _how to do this right_. If you'd like to suggest a safe, reliable way of injecting an empty transaction that is not hacky, I'm happy to accept such algorithm.

**Comment by JohanTan** [comment]
Displaying executed gtid set and gtid purged will be super helpful, so if it's possible consider this as a feature request.

**Comment by shlomi-noach** [comment]
Doing this. However something to consider is that the output can sometimes be huge.
