### ISSUE TITLE
GUI looses compact setting after relocating a slave.

### ISSUE THREAD

**Issue by gregf1** [outbrain/orchestrator#288]
Description:
When relocating a slave in compact view, the compact setting is lost.  The next time the page is refreshed after relocating the slave it shows the entire topology (which may be too big to render in the browser without compact view).

Steps to reproduce:
1. View a topology with compact=true
2. Drag a slave to a new position in the topology
3. Click refresh or wait for auto-refresh

Expected behaviour:
After relocating the slave, it retains the previous compact view setting.  ie. stays in compact view if that is enabled.

**Comment by shlomi-noach** [comment]
Thank you. This now turns into a session cookie, where previously it was based on query param.

Fixed downstream, will merge later.

**Comment by shlomi-noach** [comment]
This is fixed in https://github.com/github/orchestrator ; however I note that there was a reason for having the "compressed" flag in query-param other than in session, and that is that one would rather see _some_ clusters as compressed and others not.

So this fix introduced a change in behavior. I'll be thinking on what makes most sense.
