### ISSUE TITLE
Make host discovery work for network ranges

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#89]
Being used to nmap where I can scan a network I'd like to be able to do the same looking for a number of  MySQL servers.

So now in web/discover I have to provide a hostname and port. I'd like to also be able to provide a network range (CIDR notation?) instead and then let Orchestrator iterate over all addresses in the range looking for MySQL servers ....

So something like

Enter host name or network address would allow: 192.168.0.0/24, or 10.0.0.0/8, or perhaps the shortened versions 192.168/24, 10/8

Would be nice and would allow me to find servers more easily.

**Comment by shlomi-noach** [comment]
Why would you like to delegate a network scan to orchestrator? I would suggest you can do your own scan and let orchestrator know what you've found.

Otherwise, please be advised that you can (and we do) run "orchestrator -c discover" on all your MySQL servers once per day at some random time. This can (and is) puppetized or cheffed, so problem solved.
